apiVersion: v1
kind: Pod
metadata:
  name: partner-directory
  namespace: default
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: gitlabcred
  containers:
    - name: partner-grpc
      image: registry.gitlab.com/mikebway/container-playpen/partner-grpc:1.0.0
      ports:
        - containerPort: 50051
          protocol: TCP
    - name: partner-gql
      image: registry.gitlab.com/mikebway/container-playpen/partner-gql:1.0.1
      ports:
        - containerPort: 4000
          protocol: TCP
