apiVersion: v1
kind: Pod
metadata:
  name: partner-directory
  namespace: default
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: githubcred
  containers:
    - name: partner-grpc
      image: >-
        docker.pkg.github.com/mikebway/container-playpen/partner-grpc:1.0.0
      ports:
        - containerPort: 4000
          protocol: TCP
  restartPolicy: Never
